---
title: "Project-NYPD"
author: "Leyi Cui, Qianhui Li"
date: "3/29/2022"
output: html_document
---

Part I

```{r}
# load the NYPD dataset and the packages that we will use
NYPD <- read.csv("Data/2018_sqf_database-abbr.csv")

library(tidyverse)
library(ggplot2)
library(magrittr)
head(NYPD)
```

```{r}
# The number of stops in each month in the year 2018

# rearrange the months in order, from January to December
reorder_month <- c("January","February","March","April","May","June","July","August","September","October","November","December")
NYPD$MONTH2 = factor(NYPD$MONTH2,levels=reorder_month)
ggplot(NYPD, aes(MONTH2)) + geom_bar(alpha=0.90, colour="orange", fill="orange",width=0.75) + labs(title="", y="number of stops", x="month")
```

```{r}
# The number of stops on each day of the week

# rearrange the days in order, from Monday to Sunday
reorder_day <- c("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")
NYPD$DAY2 = factor(NYPD$DAY2,levels=reorder_day)
ggplot(NYPD, aes(DAY2)) + geom_bar(alpha=0.90, colour="salmon", fill="salmon",width=0.75) + labs(title="", y="number of stops", x="day")
```

```{r}
## Stop.Frisk.Time: the time when ppl are stopped

# Function: rounding(inputNum, totalNum)
rounding <- function(inputNum, totalNum) {
  if(is.na(inputNum)){return(FALSE)}else{
    m <- totalNum/2
    if(inputNum < m){
      # round down
      return(FALSE)
    }else{
      #round up
      return(TRUE)
    }
  }
}

hour<-NYPD$Stop.Frisk.Time
all_hour <- c()
for(i in 1:length(hour)){
  if(hour[i] == "#N/A" || is.na(hour[i]) || hour[i] == "" || hour[i] == FALSE){
    hour[i] <- "NA"
  }else{
    temp <- c(strsplit(hour[i], ":"))
    minBefore <- temp[[1]][[2]]
    hourBefore <- temp[[1]][[1]]
    if (rounding(strtoi(minBefore), 60)){
      hourAfter <- as.character(strtoi(hourBefore)+1)
      if (hourAfter == 24){
        hourAfter <- "0"
      }
    }else{
      hourAfter <- hourBefore
    }
    all_hour <- append(all_hour, hourAfter)
  }
  allH_df <- data.frame(all_hour)
}
reorder_hour <- c("0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","NA")
allH_df$all_hour = factor(allH_df$all_hour,levels=reorder_hour)
ggplot(allH_df, aes(all_hour)) + geom_bar(alpha=0.90, colour="salmon", fill="salmon",width=0.75) + labs(title="", y="number of stops", x="hour")

# Morning: from sunrise to 11:59 AM. Sunrise typically occurs around 6 AM.
# Noon: at 12:00 PM.
# Afternoon: from 12:01 PM to around 5:00 PM.
# Evening: from 5:01 PM to 8 PM, or around sunset.
# Early Night: from sunset 11:59 PM
# Late Night: from 11:59 PM to sunrise around 5:59 AM.
all_period <- c()
for(i in 1:length(allH_df$all_hour)){
  if (allH_df$all_hour[i] == "6" || allH_df$all_hour[i] == "7" || allH_df$all_hour[i] == "8" || allH_df$all_hour[i] == "9" || allH_df$all_hour[i] == "10" || allH_df$all_hour[i] == "11"){
    all_period <- append(all_period, "Morning")
  }else if(allH_df$all_hour[i] == "12"){
    all_period <- append(all_period, "Noon")
  }else if(allH_df$all_hour[i] == "13" || allH_df$all_hour[i] == "14" || allH_df$all_hour[i] == "15" || allH_df$all_hour[i] == "16"){
    all_period <- append(all_period, "Afternoon")
  }else if(allH_df$all_hour[i] == "17" || allH_df$all_hour[i] == "18" || allH_df$all_hour[i] == "19" || allH_df$all_hour[i] == "20" || allH_df$all_hour[i] == "21" || allH_df$all_hour[i] == "22" || allH_df$all_hour[i] == "23"){
    all_period <- append(all_period, "Early Night")
  }else{
    all_period <- append(all_period, "Late Night")
  }
}
allP_df <- data.frame(all_period)
reorder_period <- c("Morning", "Noon", "Afternoon", "Early Night", "Late Night")
allP_df$all_period = factor(allP_df$all_period,levels=reorder_period)
ggplot(allP_df, aes(all_period)) + geom_bar(alpha=0.90, colour="salmon", fill="salmon",width=0.75) + labs(title="", y="number of stops", x="time period")
```

```{r}
## Compare: the number of male police officers(POM) and the number of female police officers(POF)


# create POM and POF dataframes
df_male_officer <- NYPD %>% filter(ISSUING_OFFICER_RANK == "POM")
df_female_officer <- NYPD %>% filter(ISSUING_OFFICER_RANK == "POF")
head(df_male_officer)
head(df_female_officer)

# visualize the difference in numbers: frequency table, bar plot, pie chart
male_female_num <- tibble(
  type = c("male officer", "female officer"),
  freq = c(nrow(df_male_officer), nrow(df_female_officer))
)
knitr::kable(male_female_num)

p <- ggplot(data = male_female_num, mapping = aes(
  x = type, y = freq ))
p + geom_col() +
  labs(x = "number of officers", 
       y = "sex")

p2 <- ggplot(data = male_female_num, mapping = aes(
  x = 1, y = freq, fill = type ))
p2 + geom_col() +
  coord_polar(theta = "y") +
  scale_x_discrete(name = NULL, breaks = NULL) +
  scale_y_discrete(name = NULL, breaks = NULL) +
  labs(fill = "Cut")
```

```{r}
# function: to calculate the bounds of a numeric vector, will be used in the following analysis

bound <- function(x){
  Q1 <- quantile(x, .25)
  Q3 <- quantile(x, .75)
  IQR <- Q3-Q1
  bound <- c(Q1-1.5*IQR, Q3+1.5*IQR)
  return(bound)
}

```

```{r}
### Observed duration minutes.


## Overall analysis first
# Histogram --- all data(not excludes any values)
ggplot(NYPD,aes(OBSERVED_DURATION_MINUTES)) + geom_histogram(colour = "royalblue1", fill = "royalblue1",alpha=0.8) + labs(title="Distribution of Suspects' Observed Duration Minutes (including outliers)", y="count", x="observed duration mins")

# Histogram --- excludes theoretical outliers (use bound() function to calculate and exclude the theoretical outliers)
bound(NYPD$OBSERVED_DURATION_MINUTES)
ggplot(NYPD,aes(OBSERVED_DURATION_MINUTES)) + geom_histogram(breaks=seq(0,3.5,by=1), colour = "royalblue1", fill = "royalblue1",alpha=0.8) + labs(title="Distribution of Suspects' Observed Duration Minutes (excluding outliers)", y="count", x="observed duration mins")

# Histogram --- excludes large numbers (since the distribution of Odm is too right-skewed, which makes the upper bound (3.5) calculated by bound() pretty small; so we decide to set another upper bound (35) based on the distribution that we observe from the table to look at more complete data)
table(NYPD$OBSERVED_DURATION_MINUTES)
ggplot(NYPD,aes(OBSERVED_DURATION_MINUTES)) + geom_histogram(breaks=seq(0,35,by=1), colour = "royalblue1", fill = "royalblue1",alpha=0.8) + labs(title="Distribution of Suspects' Observed Duration Minutes (excluding large numbers)", y="count", x="observed duration mins")


# Observe time: male officers VS female officers(excludes large numbers)
df_pom_pof <- NYPD[NYPD$ISSUING_OFFICER_RANK == "POM" | NYPD$ISSUING_OFFICER_RANK == "POF",]
ggplot(df_pom_pof, aes(x = ISSUING_OFFICER_RANK, y = OBSERVED_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 35))

# Observe time: male officers VS female officers (excludes theoretical outliers)
ggplot(df_pom_pof, aes(x = ISSUING_OFFICER_RANK, y = OBSERVED_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 3.5))




### Stop duration minutes.


## Overall analysis first
# Histogram --- all data(not excludes any values)
ggplot(NYPD,aes(STOP_DURATION_MINUTES)) + geom_histogram(colour = "royalblue3", fill = "royalblue3",alpha=0.8) + labs(title="Distribution of Suspects' Stopped Duration Minutes (including outliers)", y="count", x="stop duration mins") 

# Histogram --- excludes theoretical outliers (use bound() function to calculate and exclude the theoretical outliers)
bound(NYPD$STOP_DURATION_MINUTES)
ggplot(NYPD,aes(STOP_DURATION_MINUTES)) + geom_histogram(breaks=seq(0,30,by=1), colour = "royalblue1", fill = "royalblue1",alpha=0.8) + labs(title="Distribution of Suspects' Stopped Duration Minutes (excluding outliers)", y="count", x="stop duration mins")

# Histogram --- excludes large numbers (since the distribution of Sdm is too right-skewed, which makes the upper bound (30) calculated by bound() small; so we decide to set another upper bound (50) based on the distribution that we observe from the table to look at more complete data)
table(NYPD$STOP_DURATION_MINUTES)
ggplot(NYPD,aes(STOP_DURATION_MINUTES)) + geom_histogram(breaks=seq(0,50,by=1), colour = "royalblue3", fill = "royalblue3",alpha=0.8) + labs(title="Distribution of Suspects' Stopped Duration Minutes (excluding large numbers)", y="count", x="stop duration mins") 



# Stop time: male officers VS female officers(excludes large numbers)
df_pom_pof <- NYPD[NYPD$ISSUING_OFFICER_RANK == "POM" | NYPD$ISSUING_OFFICER_RANK == "POF",]
ggplot(df_pom_pof, aes(x = ISSUING_OFFICER_RANK, y = STOP_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 50))

# Observe time: male officers VS female officers (excludes theoretical outliers)
ggplot(df_pom_pof, aes(x = ISSUING_OFFICER_RANK, y = STOP_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 30))




## Relation between Observed Duration Minutes and Stop Duration Minutes 

# all data(Not excludes any values)
ggplot(NYPD, aes(OBSERVED_DURATION_MINUTES, STOP_DURATION_MINUTES)) + geom_point() + labs(title="The Relation between Observed Time and Stop Time", subtitle="(with all data)", y="stop duration mins", x="observed duration mins")


# excludes large numbers
ggplot(NYPD, aes(OBSERVED_DURATION_MINUTES, STOP_DURATION_MINUTES)) + geom_point() + coord_cartesian(xlim=c(0, 35), ylim=c(0, 50)) + labs(title="The Relation between Observed Time and Stop Time", subtitle="(excluding large numbers)", y="stop duration mins", x="observed duration mins")


# excludes theoretical outliers
ggplot(NYPD, aes(OBSERVED_DURATION_MINUTES, STOP_DURATION_MINUTES)) + geom_point() + coord_cartesian(xlim=c(0, 3.5), ylim=c(0, 30)) + labs(title="The Relation between Observed Time and Stop Time", subtitle="(excluding outliers)", y="stop duration mins", x="observed duration mins")


```

```{r}
### Suspected crime description.
unique(NYPD$SUSPECTED_CRIME_DESCRIPTION)

## since there are too many types of crimes, we divide them into 4 main categories:
# THEFT: "GRAND LARCENY AUTO", "BURGLARY", "CPSP(criminal possession of stolen property)", "GRAND LARCENY", "PETIT LARCENY", "ROBBERY", "THEFT OF SERVICES", "UNAUTHORIZED USE OF A VEHICLE";
# ATTACK AND DAMAGE: "AUTO STRIPPIG", "ASSAULT", "CRIMINAL TRESPASS", "FORCIBLE TOUCHING", "MENACING", "MURDER", "RECKLESS ENDANGERMENT", "PROSTITUTION", "RAPE";
# POSSESSION, SALE OF PROHIBITED ITMES: "CPW(criminal possession of a weapon)", "CRIMINAL POSSESSION OF CONTROLLED SUBSTANCE", "CRIMINAL POSSESSION OF FORGED INSTRUMENT", "CRIMINAL POSSESSION OF MARIHUANA", "CRIMINAL SALE OF CONTROLLED SUBSTANCE", "CRIMINAL SALE OF MARIHUANA";
# Others: "CRIMINAL MISCHIEF", "MAKING GRAFFITI", "TERRORISM", "OTHER";

NYPD$CRIME_CATEGORIZATION <- vector(mode='character', length(NYPD$SUSPECTED_CRIME_DESCRIPTION))
for(i in seq_along(NYPD$SUSPECTED_CRIME_DESCRIPTION)){
  if(NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "GRAND LARCENY AUTO" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "BURGLARY" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CPSP" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "GRAND LARCENY" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "PETIT LARCENY" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "ROBBERY" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "THEFT OF SERVICES" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "UNAUTHORIZED USE OF A VEHICLE" ){
    NYPD$CRIME_CATEGORIZATION[i] <- "Theft"
    }else if (NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "AUTO STRIPPIG" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "ASSAULT" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CRIMINAL TRESPASS" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "FORCIBLE TOUCHING" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "MENACING" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "MURDER" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "RECKLESS ENDANGERMENT" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "PROSTITUTION" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "RAPE" ) {
      NYPD$CRIME_CATEGORIZATION[i] <- "Attack and Damage"
    }else if (NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CPW" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CRIMINAL POSSESSION OF CONTROLLED SUBSTANCE" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CRIMINAL POSSESSION OF FORGED INSTRUMENT" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CRIMINAL POSSESSION OF MARIHUANA" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CRIMINAL SALE OF CONTROLLED SUBSTANCE" | NYPD$SUSPECTED_CRIME_DESCRIPTION[i] == "CRIMINAL SALE OF MARIHUANA"){
        NYPD$CRIME_CATEGORIZATION[i] <- "Possession,Sale of Prohibited Items"
      }
        
        else{
        NYPD$CRIME_CATEGORIZATION[i] <- "Others"
      }
  
}

ggplot(NYPD, aes(CRIME_CATEGORIZATION)) + geom_bar(alpha=0.90, colour="red4", fill="red4",width=0.5) + labs(title= "Different Types of Crimes Suspected", y="count", x="types of crimes suspected")


## And then we make 4 separate bar plots -- 1 for each category, showing the distribution of the different crime descriptions inside each category


# Theft:
df_theft <- NYPD[NYPD$CRIME_CATEGORIZATION == "Theft",]
sum_theft <- NYPD %>% filter(CRIME_CATEGORIZATION == "Theft") %>% nrow()
print(paste("sum of theft: ",sum_theft))

ggplot(df_theft, aes(SUSPECTED_CRIME_DESCRIPTION)) + geom_bar(alpha=0.90, colour="red4", fill="red4",width=0.5) + labs(title= "Theft Suspected", y="count", x="types of theft suspected") + theme(axis.text.x=element_text(size=4.1))


# Attack and Damage:
df_att_dam <- NYPD[NYPD$CRIME_CATEGORIZATION == "Attack and Damage",]
sum_att_dam <- NYPD %>% filter(CRIME_CATEGORIZATION == "Attack and Damage") %>% nrow()
print(paste("sum of attack and damage: ",sum_att_dam))

ggplot(df_att_dam, aes(SUSPECTED_CRIME_DESCRIPTION)) + geom_bar(alpha=0.90, colour="red4", fill="red4",width=0.5) + labs(title= "Attack and Damage Suspected", y="count", x="types of attack and damage suspected") + theme(axis.text.x=element_text(size=4.5))


# Possession, Sale of Prohibited Items:
df_proh_items <- NYPD[NYPD$CRIME_CATEGORIZATION == "Possession,Sale of Prohibited Items",]
sum_prob_items <- NYPD %>% filter(CRIME_CATEGORIZATION == "Possession,Sale of Prohibited Items") %>% nrow()
print(paste("sum of possession,sale of prohibited items: ",sum_prob_items))

ggplot(df_proh_items, aes(SUSPECTED_CRIME_DESCRIPTION)) + geom_bar(alpha=0.90, colour="red4", fill="red4",width=0.5) + labs(title= "Possession,Sale of Prohibited Items Suspected", y="count", x="types of possesion,sale of prohibited items suspected") + theme(axis.text.x=element_text(size=3))


# Others:
df_others <- NYPD[NYPD$CRIME_CATEGORIZATION == "Others",]
sum_others <- NYPD %>% filter(CRIME_CATEGORIZATION == "Others") %>% nrow()
print(paste("sum of other crimes: ",sum_others))

ggplot(df_others, aes(SUSPECTED_CRIME_DESCRIPTION)) + geom_bar(alpha=0.90, colour="red4", fill="red4",width=0.5) + labs(title= "Other Crimes Suspected", y="count", x="types of crimes")
```



```{r}
## Frisk Flag and Search Flag.
## "Search is more intensive than frisk. Frisk is to pat down the suspects to see whether they have weapons, while search is to probe for more evidence, other than weapons."


# Overall probabilities of frisked and searched
probability_frisk <- NYPD %>% select(FRISKED_FLAG) %>% unlist() %>% mean()
print(probability_frisk)
probability_search <- NYPD %>% select(SEARCHED_FLAG) %>% unlist() %>% mean()
print(probability_search)



# We divide it into 4 categories: both frisked and searched, only frisked, only searched, neither frisked nor searched
# Each suspect can be both frisked and searched

NYPD$FRISK_AND_SEARCH <- vector(mode='character', length(NYPD$FRISKED_FLAG))
for(i in seq_along(NYPD$FRISK_AND_SEARCH)){
  if(NYPD$FRISKED_FLAG[i] == "1" & NYPD$SEARCHED_FLAG[i] == "1"){
    NYPD$FRISK_AND_SEARCH[i] <- "Frisked and Searched"
    }else if (NYPD$FRISKED_FLAG[i] == "1" & NYPD$SEARCHED_FLAG[i] == "0") {
      NYPD$FRISK_AND_SEARCH[i] <- "Only Frisked"
      }else if (NYPD$FRISKED_FLAG[i] == "0" & NYPD$SEARCHED_FLAG[i] == "1") {
        NYPD$FRISK_AND_SEARCH[i] <- "Only Searched"
      }else{
        NYPD$FRISK_AND_SEARCH[i] <- "Neither Frisked Nor Searched"
      }
  
}

table(NYPD$FRISK_AND_SEARCH)
ggplot(NYPD, aes(FRISK_AND_SEARCH)) + geom_bar(alpha=0.90, colour="mediumpurple3", fill="mediumpurple3",width=0.5) + labs(title= "The Number of Suspects Frisked or Searched", y="count", x="Frisked and Searched")



# Observed time: only frisked VS only searched VS both VS none(excludes large numbers)
ggplot(NYPD, aes(x = FRISK_AND_SEARCH, y = OBSERVED_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 35))

# Observed time: only frisked VS only searched VS both VS none (excludes theoretical outliers)
bound(NYPD$OBSERVED_DURATION_MINUTES)
ggplot(NYPD, aes(x = FRISK_AND_SEARCH, y = OBSERVED_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 3.5))


# Stop time: only frisked VS only searched VS both VS none (excludes large numbers)
ggplot(NYPD, aes(x = FRISK_AND_SEARCH, y = STOP_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 50))

# Stop time: only frisked VS only searched VS both VS none (excludes theoretical outliers)
bound(NYPD$STOP_DURATION_MINUTES)
ggplot(NYPD, aes(x = FRISK_AND_SEARCH, y = STOP_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 30))


```

```{r}
# Whether police officers are in uniform when stopping suspects.
NYPD[NYPD$OFFICER_IN_UNIFORM_FLAG==0,"OFFICER_IN_UNIFORM_FLAG"] <- "not wearing uniform"
NYPD[NYPD$OFFICER_IN_UNIFORM_FLAG==1,"OFFICER_IN_UNIFORM_FLAG"] <- "wearing uniform"
table(NYPD$OFFICER_IN_UNIFORM_FLAG)
ggplot(NYPD, aes(OFFICER_IN_UNIFORM_FLAG)) + geom_bar(alpha=0.90, colour="royalblue1", fill="royalblue1",width=0.75) + labs(title="", y="number of officers", x="officer in uniform")

```

```{r}
## Suspects Arrested (implies accuracy of stops) $ Accuracy in relation to different factors(sex, race,etc.)

# the number of suspects finally arrested and not arrested
NYPD[NYPD$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "suspect not arrested"
NYPD[NYPD$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "suspect arrested"
table(NYPD$SUSPECT_ARRESTED_FLAG)
ggplot(NYPD, aes(SUSPECT_ARRESTED_FLAG)) + geom_bar(alpha=0.90, colour="royalblue1", fill="royalblue1",width=0.75) + labs(title="", y="number of stops", x="number os arrests")

# accuracy of overall stops
overall_a_acc <- 3115/11018
print(overall_a_acc)


## male officers' accuracy vs female officers' accuracy
df_male_officer[df_male_officer$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "male_suspect not arrested"
df_male_officer[df_male_officer$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "male_suspect arrested"
table(df_male_officer$SUSPECT_ARRESTED_FLAG)
df_female_officer[df_female_officer$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "female_suspect not arrested"
df_female_officer[df_female_officer$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "female_suspect arrested"
table(df_female_officer$SUSPECT_ARRESTED_FLAG)
male_a_acc <- 2639/(2639+6612)
print(male_a_acc)
female_a_acc <- 321/(321+904)
print(female_a_acc)


## Observed time in relation to Accuracy
# scatter plot: observed time VS accuracy
ggplot(data=NYPD) + geom_point(mapping = aes(x = OBSERVED_DURATION_MINUTES, y = SUSPECT_ARRESTED_FLAG))
# excludes large numbers
ggplot(data=NYPD) + geom_point(mapping = aes(x = OBSERVED_DURATION_MINUTES, y = SUSPECT_ARRESTED_FLAG)) + coord_cartesian(xlim=c(0, 35))
# excludes theoretical outliers
bound(NYPD$OBSERVED_DURATION_MINUTES)
ggplot(data=NYPD) + geom_point(mapping = aes(x = OBSERVED_DURATION_MINUTES, y = SUSPECT_ARRESTED_FLAG)) + coord_cartesian(xlim=c(0, 3.5))


## Stop time in relation to Accuracy
# scatter plot: stop time VS accuracy
ggplot(data=NYPD) + geom_point(mapping = aes(x = STOP_DURATION_MINUTES, y = SUSPECT_ARRESTED_FLAG))
# excludes large numbers
ggplot(data=NYPD) + geom_point(mapping = aes(x = STOP_DURATION_MINUTES, y = SUSPECT_ARRESTED_FLAG)) + coord_cartesian(xlim=c(0, 50))
# excludes theoretical outliers
bound(NYPD$STOP_DURATION_MINUTES)
ggplot(data=NYPD) + geom_point(mapping = aes(x = OBSERVED_DURATION_MINUTES, y = SUSPECT_ARRESTED_FLAG)) + coord_cartesian(xlim=c(0, 30))


## Suspects' Ages in relation to Accuracy
# scatter plot: age VS accuracy
# excludes 0s
ggplot(data=NYPD) + geom_point(mapping = aes(x = SUSPECT_REPORTED_AGE, y = SUSPECT_ARRESTED_FLAG)) + coord_cartesian(xlim=c(1, 90))
# excludes theoretical outliers
bound(NYPD$SUSPECT_REPORTED_AGE)
ggplot(data=NYPD) + geom_point(mapping = aes(x = SUSPECT_REPORTED_AGE, y = SUSPECT_ARRESTED_FLAG)) + coord_cartesian(xlim=c(1, 61))


## Suspects' Sex in relation to Accuracy
# create dataframes on SUSPECT_SEX
df_male_suspect <- NYPD[NYPD$SUSPECT_SEX == "MALE",]
df_female_suspect <- NYPD[NYPD$SUSPECT_SEX == "FEMALE",]
head(df_male_suspect)
head(df_female_suspect)

# accuracy on SUSPECT_SEX
df_male_suspect[df_male_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "male_suspect not arrested"
df_male_suspect[df_male_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "male_suspect arrested"
table(df_male_suspect$SUSPECT_ARRESTED_FLAG)
df_female_suspect[df_female_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "female_suspect not arrested"
df_female_suspect[df_female_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "female_suspect arrested"
table(df_female_suspect$SUSPECT_ARRESTED_FLAG)
male_a_s_acc <- 2786/(2786+7139)
print(male_a_s_acc)
female_a_s_acc <- 311/(311+703)
print(female_a_s_acc)


## Suspects' Race in relation to Accuracy
# create dataframes on SUSPECT_RACE_DESCRIPTION
df_AIAN_suspect <- NYPD[NYPD$SUSPECT_RACE_DESCRIPTION == "AMERICAN INDIAN/ALASKAN NATIVE",]
df_WH_suspect <- NYPD[NYPD$SUSPECT_RACE_DESCRIPTION == "WHITE HISPANIC",]
df_BH_suspect <- NYPD[NYPD$SUSPECT_RACE_DESCRIPTION == "BLACK HISPANIC",]
df_API_suspect <- NYPD[NYPD$SUSPECT_RACE_DESCRIPTION == "ASIAN / PACIFIC ISLANDER",]
df_W_suspect <- NYPD[NYPD$SUSPECT_RACE_DESCRIPTION == "WHITE",]
df_B_suspect <- NYPD[NYPD$SUSPECT_RACE_DESCRIPTION == "BLACK",]
df_0_suspect <- NYPD[NYPD$SUSPECT_RACE_DESCRIPTION == "0",]
head(df_AIAN_suspect)
head(df_WH_suspect)
head(df_BH_suspect)
head(df_API_suspect)
head(df_W_suspect)
head(df_B_suspect)
head(df_0_suspect)

# accuracy on SUSPECT_RACE_DESCRIPTION
df_AIAN_suspect[df_AIAN_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "aian_suspect not arrested"
df_AIAN_suspect[df_AIAN_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "aian_suspect arrested"
table(df_AIAN_suspect$SUSPECT_ARRESTED_FLAG)
df_WH_suspect[df_WH_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "wh_suspect not arrested"
df_WH_suspect[df_WH_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "wh_suspect arrested"
table(df_WH_suspect$SUSPECT_ARRESTED_FLAG)
df_BH_suspect[df_BH_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "bh_suspect not arrested"
df_BH_suspect[df_BH_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "bh_suspect arrested"
table(df_BH_suspect$SUSPECT_ARRESTED_FLAG)
df_API_suspect[df_API_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "api_suspect not arrested"
df_API_suspect[df_API_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "api_suspect arrested"
table(df_API_suspect$SUSPECT_ARRESTED_FLAG)
df_W_suspect[df_W_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "w_suspect not arrested"
df_W_suspect[df_W_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "w_suspect arrested"
table(df_W_suspect$SUSPECT_ARRESTED_FLAG)
df_B_suspect[df_B_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "b_suspect not arrested"
df_B_suspect[df_B_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "b_suspect arrested"
table(df_B_suspect$SUSPECT_ARRESTED_FLAG)
df_0_suspect[df_0_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "0_suspect not arrested"
df_0_suspect[df_0_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "0_suspect arrested"
table(df_0_suspect$SUSPECT_ARRESTED_FLAG)

aian_a_s_acc <- 4/(4+12)
print(aian_a_s_acc)
wh_a_s_acc <- 783/(783+1628)
print(wh_a_s_acc)
bh_a_s_acc <- 252/(252+726)
print(bh_a_s_acc)
api_a_s_acc <- 51/(51+170)
print(api_a_s_acc)
w_a_s_acc <- 303/(303+771)
print(w_a_s_acc)
b_a_s_acc <- 1709/(1709+4532)
print(b_a_s_acc)
zero_a_s_acc <- 13/(13+54)
print(zero_a_s_acc)


## Suspects' Heights in relation to Accuracy
# scatter plot: suspect height VS accuracy
ggplot(data=NYPD) + geom_point(mapping = aes(x = SUSPECT_HEIGHT, y = SUSPECT_ARRESTED_FLAG))


## Suspects' Weights in relation to Accuracy
# scatter plot: suspect weight VS accuracy
ggplot(data=NYPD) + geom_point(mapping = aes(x = SUSPECT_WEIGHT, y = SUSPECT_ARRESTED_FLAG))



## Suspects' Body Build Types in relation to Accuracy
# create dataframes on SUSPECT_BODY_BUILD_TYPE
df_01_suspect <- NYPD[NYPD$SUSPECT_BODY_BUILD_TYPE == "0",]
df_HEA_suspect <- NYPD[NYPD$SUSPECT_BODY_BUILD_TYPE == "HEA",]
df_MED_suspect <- NYPD[NYPD$SUSPECT_BODY_BUILD_TYPE == "MED",]
df_THN_suspect <- NYPD[NYPD$SUSPECT_BODY_BUILD_TYPE == "THN",]
df_U_suspect <- NYPD[NYPD$SUSPECT_BODY_BUILD_TYPE == "U",]
df_XXX_suspect <- NYPD[NYPD$SUSPECT_BODY_BUILD_TYPE == "XXX",]
head(df_01_suspect)
head(df_HEA_suspect)
head(df_MED_suspect)
head(df_THN_suspect)
head(df_U_suspect)
head(df_XXX_suspect)

# accuracy on SUSPECT_BODY_BUILD_TYPE
df_01_suspect[df_01_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "01_suspect not arrested"
df_01_suspect[df_01_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "01_suspect arrested"
table(df_01_suspect$SUSPECT_ARRESTED_FLAG)
df_HEA_suspect[df_HEA_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "hea_suspect not arrested"
df_HEA_suspect[df_HEA_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "hea_suspect arrested"
table(df_HEA_suspect$SUSPECT_ARRESTED_FLAG)
df_MED_suspect[df_MED_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "med_suspect not arrested"
df_MED_suspect[df_MED_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "med_suspect arrested"
table(df_MED_suspect$SUSPECT_ARRESTED_FLAG)
df_THN_suspect[df_THN_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "thn_suspect not arrested"
df_THN_suspect[df_THN_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "thn_suspect arrested"
table(df_THN_suspect$SUSPECT_ARRESTED_FLAG)
df_U_suspect[df_U_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "u_suspect not arrested"
df_U_suspect[df_U_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "u_suspect arrested"
table(df_U_suspect$SUSPECT_ARRESTED_FLAG)
df_XXX_suspect[df_XXX_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "xxx_suspect not arrested"
df_XXX_suspect[df_XXX_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "xxx_suspect arrested"
table(df_XXX_suspect$SUSPECT_ARRESTED_FLAG)

zero1_a_s_acc <- 22/(22+126)
print(zero1_a_s_acc)
hea_a_s_acc <- 299/(299+757)
print(hea_a_s_acc)
med_a_s_acc <- 1098/(1098+3009)
print(med_a_s_acc)
thn_a_s_acc <- 1580/(1580+3738)
print(thn_a_s_acc)
u_a_s_acc <- 105/(105+226)
print(u_a_s_acc)
xxx_a_s_acc <- 11/(11+37)
print(xxx_a_s_acc)


## Suspects' Stopped Borough in relation to Accuracy
# create dataframe on STOP_LOCATION_BORO_NAME
df_BRONX_suspect <- NYPD[NYPD$STOP_LOCATION_BORO_NAME == "BRONX",]
df_BROOKLYN_suspect <- NYPD[NYPD$STOP_LOCATION_BORO_NAME == "BROOKLYN",]
df_MANHATTAN_suspect <- NYPD[NYPD$STOP_LOCATION_BORO_NAME == "MANHATTAN",]
df_QUEENS_suspect <- NYPD[NYPD$STOP_LOCATION_BORO_NAME == "QUEENS",]
df_SI_suspect <- NYPD[NYPD$STOP_LOCATION_BORO_NAME == "STATEN ISLAND",]
head(df_BRONX_suspect)
head(df_BROOKLYN_suspect)
head(df_MANHATTAN_suspect)
head(df_QUEENS_suspect)
head(df_SI_suspect)

# accuracy on STOP_LOCATION_BORO_NAME
df_BRONX_suspect[df_BRONX_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "BRONX_suspect not arrested"
df_BRONX_suspect[df_BRONX_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "BRONX_suspect arrested"
table(df_BRONX_suspect$SUSPECT_ARRESTED_FLAG)
df_BROOKLYN_suspect[df_BROOKLYN_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "BROOKLYN_suspect not arrested"
df_BROOKLYN_suspect[df_BROOKLYN_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "BROOKLYN_suspect arrested"
table(df_BROOKLYN_suspect$SUSPECT_ARRESTED_FLAG)
df_MANHATTAN_suspect[df_MANHATTAN_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "MANHATTAN_suspect not arrested"
df_MANHATTAN_suspect[df_MANHATTAN_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "MANHATTAN_suspect arrested"
table(df_MANHATTAN_suspect$SUSPECT_ARRESTED_FLAG)
df_QUEENS_suspect[df_QUEENS_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "QUEENS_suspect not arrested"
df_QUEENS_suspect[df_QUEENS_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "QUEENS_suspect arrested"
table(df_QUEENS_suspect$SUSPECT_ARRESTED_FLAG)
df_SI_suspect[df_SI_suspect$SUSPECT_ARRESTED_FLAG==0,"SUSPECT_ARRESTED_FLAG"] <- "SI_suspect not arrested"
df_SI_suspect[df_SI_suspect$SUSPECT_ARRESTED_FLAG==1,"SUSPECT_ARRESTED_FLAG"] <- "SI_suspect arrested"
table(df_SI_suspect$SUSPECT_ARRESTED_FLAG)

BRONX_a_s_acc <- 626/(626+1705)
print(BRONX_a_s_acc)
BROOKLYN_a_s_acc <- 912/(912+2720)
print(BROOKLYN_a_s_acc)
MANHATTAN_a_s_acc <- 901/(901+1956)
print(MANHATTAN_a_s_acc)
QUEENS_a_s_acc <- 554/(554+1294)
print(QUEENS_a_s_acc)
SI_a_s_acc <- 122/(122+218)
print(SI_a_s_acc)
```

```{r}
# function1: variable X VS observe duration minutes (box plots && scatterpLots)
observe_time_relation <- function(m){
  if(class(m) == "character"){
    ggplot(NYPD, aes(x = m, y = OBSERVED_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 35))
  }else{
    ggplot(NYPD, aes(m, OBSERVED_DURATION_MINUTES)) + geom_point() + coord_cartesian(ylim=c(0, 35)) 
  }
}


# function2: variable X VS stop duration minutes (box plots && scatterpLots)
stop_time_relation <- function(n){
  if(class(n) == "character"){
    ggplot(NYPD, aes(x = n, y = STOP_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 50))
  }else{
    ggplot(NYPD, aes(n, STOP_DURATION_MINUTES)) + geom_point() + coord_cartesian(ylim=c(0, 50)) 
  }
}

observe_time_relation(NYPD$SUSPECT_SEX)


```

```{r}
## Suspect Reported Ages

# overall visualization
class(NYPD$SUSPECT_REPORTED_AGE)
ggplot(NYPD,aes(SUSPECT_REPORTED_AGE)) + geom_histogram(colour = "orange3", fill = "orange3",alpha=0.8) + labs(title="Distribution of Suspect Reported Ages ", y="count", x="suspect reported age")

# VS observed time
observe_time_relation(NYPD$SUSPECT_REPORTED_AGE) + labs(title="Relation between Suspect Reported Ages and Observed Time ", y="observed duration mins", x="suspect reported ages")

# VS stop time
stop_time_relation(NYPD$SUSPECT_REPORTED_AGE) + labs(title="Relation between Suspect Reported Ages and Stop Time ", y="stopped duration mins", x="suspect reported ages")


```

```{r}
##  SUSPECT SEX

# overall visualization
class(NYPD$SUSPECT_SEX)
ggplot(NYPD, aes(SUSPECT_SEX)) + geom_bar(alpha=0.90, colour="salmon", fill="salmon",width=0.75) + labs(title="Distribution of Suspect Sex", y="count", x="suspect sex")

# VS observed time
observe_time_relation(NYPD$SUSPECT_SEX) + labs(title="Observed Time for Different Suspect Sex", y="observed duration mins", x="suspect sex")

# VS stop time
stop_time_relation(NYPD$SUSPECT_SEX) + labs(title="Stop Time for Different Suspect Sex", y="stopped duration mins", x="suspect sex")


```

```{r}
## SUSPECT RACE DESCRIPTION

# overall visualization
class(NYPD$SUSPECT_RACE_DESCRIPTION)
ggplot(NYPD, aes(SUSPECT_RACE_DESCRIPTION)) + geom_bar(alpha=0.90, colour="salmon", fill="salmon",width=0.5) + labs(title="Distribution of Suspect Race Description", y="count", x="suspect race description") + theme(axis.text.x=element_text(size=4.3))

# VS observed time
observe_time_relation(NYPD$SUSPECT_RACE_DESCRIPTION) + labs(title="Observed Time for Different Suspect Race Descriptions", y="observed duration mins", x="suspect race descriptions") +theme(axis.text.x=element_text(size=4.3))

# VS stop time
stop_time_relation(NYPD$SUSPECT_RACE_DESCRIPTION) + labs(title="Stop Time for Different Suspect Race Descriptions", y="stopped duration mins", x="suspect race descriptions") +theme(axis.text.x=element_text(size=4.3))
```

```{r}
## SUSPECT HEIGHT 


# overall visualization
NYPD$SUSPECT_HEIGHT <- as.numeric(NYPD$SUSPECT_HEIGHT)
ggplot(NYPD,aes(SUSPECT_HEIGHT)) + geom_histogram(colour = "orange3", fill = "orange3",alpha=0.8) + labs(title="Distribution of Suspect Heights", y="count", x="suspect height")

# VS observed time
observe_time_relation(NYPD$SUSPECT_HEIGHT) + labs(title="Relation between Suspect Height and Observed Time ", y="observed duration mins", x="suspect height")

# VS stop time
stop_time_relation(NYPD$SUSPECT_HEIGHT) + labs(title="Relation between Suspect Height and Stop Time ", y="stopped duration mins", x="suspect height")

```

```{r}
# SUSPECT WEIGHT


# overall visualization
NYPD$SUSPECT_WEIGHT <- as.numeric(NYPD$SUSPECT_WEIGHT)
ggplot(NYPD,aes(SUSPECT_WEIGHT)) + geom_histogram(colour = "orange3", fill = "orange3",alpha=0.8) + labs(title="Distribution of Suspect Weights", y="count", x="suspect weight")

# VS observed time
observe_time_relation(NYPD$SUSPECT_WEIGHT) + labs(title="Relation between Suspect Weight and Observed Time ", y="observed duration mins", x="suspect weight")

# VS stop time
stop_time_relation(NYPD$SUSPECT_WEIGHT) + labs(title="Relation between Suspect Weight and Stop Time ", y="stopped duration mins", x="suspect weight")

```

```{r}
# SUSPECT BODY BUILD TYPE

# overall visualization
class(NYPD$SUSPECT_BODY_BUILD_TYPE)
ggplot(NYPD, aes(SUSPECT_BODY_BUILD_TYPE)) + geom_bar(alpha=0.90, colour="tomato", fill="tomato",width=0.5) + labs(title="Distribution of Suspect Body Build Type", y="count", x="suspect body build type")

# VS observed time
observe_time_relation(NYPD$SUSPECT_BODY_BUILD_TYPE) + labs(title="Observed Time for Different Suspect Body Build Types", y="observed duration mins", x="suspect body build type")

# VS stop time
stop_time_relation(NYPD$SUSPECT_BODY_BUILD_TYPE) + labs(title="Stop Time for Different Suspect Body Build Types", y="stopped duration mins", x="suspect body build type") 
```

```{r}
# SUSPECT EYE COLOR


# overall visualization
unique(NYPD$SUSPECT_EYE_COLOR)
ggplot(NYPD, aes(SUSPECT_EYE_COLOR)) + geom_bar(alpha=0.90, colour="tomato", fill="tomato",width=0.5) + labs(title="Distribution of Suspect Eye Colors", y="count", x="suspect eye color")

# VS observed time
observe_time_relation(NYPD$SUSPECT_EYE_COLOR) + labs(title="Observed Time for Different Suspect Eye Colors", y="observed duration mins", x="suspect eye color") 

# VS stop time
stop_time_relation(NYPD$SUSPECT_EYE_COLOR) + labs(title="Stop Time for Different Suspect Eye Colors", y="stopped duration mins", x="suspect eye color") 
```

```{r}
# SUSPECT HAIR COLOR


# overall visualization
unique(NYPD$SUSPECT_HAIR_COLOR)
ggplot(NYPD, aes(SUSPECT_HAIR_COLOR)) + geom_bar(alpha=0.90, colour="tomato", fill="tomato",width=0.5) + labs(title="Distribution of Suspect Hair Colors", y="count", x="suspect hair color")

# VS observed time
observe_time_relation(NYPD$SUSPECT_HAIR_COLOR) + labs(title="Observed Time for Different Suspect Hair Colors", y="observed duration mins", x="suspect hair color") 

# VS stop time
stop_time_relation(NYPD$SUSPECT_HAIR_COLOR) + labs(title="Stop Time for Different Suspect Hair Colors", y="stopped duration mins", x="suspect hair color") 
```

```{r}
# STOP LOCATION BOROUGH NAME


# overall visualization
table(NYPD$STOP_LOCATION_BORO_NAME)
ggplot(NYPD, aes(STOP_LOCATION_BORO_NAME)) + geom_bar(alpha=0.90, colour="orange3", fill="orange3",width=0.5) + labs(title="Distribution of Suspect Location Boroughs", y="count", x="stop borough")

# VS observed time
observe_time_relation(NYPD$STOP_LOCATION_BORO_NAME) + labs(title="Observed Time for Different Suspect Location Boroughs", y="observed duration mins", x="suspect borough") 

# VS stop time
stop_time_relation(NYPD$STOP_LOCATION_BORO_NAME) + labs(title="Stop Time for Different Suspect Location Boroughs", y="stopped duration mins", x="suspect borough") 

# To verify function1 and function2
# Borough VS Stop Time
mean(NYPD$STOP_DURATION_MINUTES)
median(NYPD$STOP_DURATION_MINUTES)
ggplot(NYPD, aes(x = STOP_LOCATION_BORO_NAME, y = STOP_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 50))

# Borough VS Observe Time
mean(NYPD$OBSERVED_DURATION_MINUTES)
median(NYPD$OBSERVED_DURATION_MINUTES)
ggplot(NYPD, aes(x = STOP_LOCATION_BORO_NAME, y = OBSERVED_DURATION_MINUTES)) + geom_boxplot() + coord_cartesian(ylim=c(0, 35))
```

Part II

```{r}
# We use chi-squared test of independence to compare the proportion. Here, we have:
# Null hypothesis: There is no association between category A and category B
# Alternative hypothesis: There is an association between category A and category B

install.packages("dplyr")
library(dplyr)
library(ggplot2)

#head(NYPD)

#Select the variables we want to analyze: FRISKED_FLAG, SEARCHED_FLAG
analysis_vars <- NYPD %>%
       select(FRISKED_FLAG, SEARCHED_FLAG) %>%
       filter(FRISKED_FLAG %in% c("0", "1"), SEARCHED_FLAG %in% c("0", "1"))

head(analysis_vars)

#Let's investigate to see if there is an association between FRISKED_FLAG and SEARCHED_FLAG
frisked_searched <- table(analysis_vars$FRISKED_FLAG, analysis_vars$SEARCHED_FLAG)
print(frisked_searched)

#Create a bar graph of FRISKED_FLAG by SEARCHED_FLAG
ggplot(analysis_vars, aes(FRISKED_FLAG)) + geom_bar(aes(fill = SEARCHED_FLAG))

#Conduct a Chi-Squared Test of Independence
chisq.test(analysis_vars$FRISKED_FLAG, analysis_vars$SEARCHED_FLAG)
```

```{r}
# Chi-square Test

#Select the variables we want to analyze: OFFICER_IN_UNIFORM_FLAG, SUSPECT_ARRESTED_FLAG
analysis_vars2 <- NYPD %>%
       select(OFFICER_IN_UNIFORM_FLAG, SUSPECT_ARRESTED_FLAG) %>%
       filter(OFFICER_IN_UNIFORM_FLAG %in% c("0", "1"), SUSPECT_ARRESTED_FLAG %in% c("0", "1"))

head(analysis_vars2)

#Let's investigate to see if there is an association between OFFICER_IN_UNIFORM_FLAG and SUSPECT_ARRESTED_FLAG
uniform_arrested <- table(analysis_vars2$OFFICER_IN_UNIFORM_FLAG, analysis_vars2$SUSPECT_ARRESTED_FLAG)
print(uniform_arrested)

#Create a bar graph of OFFICER_IN_UNIFORM_FLAG by SUSPECT_ARRESTED_FLAG
ggplot(analysis_vars2, aes(OFFICER_IN_UNIFORM_FLAG)) + geom_bar(aes(fill = SUSPECT_ARRESTED_FLAG))
```

```{r}
### Linear Regression 1: Observe Time VS. Stop Time


## First roughly observe the linear relationship between Observe Mins and Stop Mins
# scatter plot of observe time(x) vs. stop time(y), done above
ggplot(NYPD, aes(OBSERVED_DURATION_MINUTES, STOP_DURATION_MINUTES)) + geom_point() + labs(title="The Relation between Observed Time and Stop Time", subtitle="(with all data)", y="stop duration mins", x="observed duration mins")

# calculate the correlation -- seems a moderate/weak positive correlation
corr_observet_stopt <- cor(NYPD$OBSERVED_DURATION_MINUTES,NYPD$STOP_DURATION_MINUTES)
print(paste("correlation between observe mins and stop mins is",corr_observet_stopt))

# generate a line of best fit
ggplot(NYPD, aes(OBSERVED_DURATION_MINUTES, STOP_DURATION_MINUTES)) + geom_point() + geom_smooth(method="lm")



## Build the linear regression model and check whether the residuals fit the assumptions
observet_stopt_model <- lm(STOP_DURATION_MINUTES ~ OBSERVED_DURATION_MINUTES, data = NYPD)
print(observet_stopt_model)

# generate histogram, normal probability plot of residuals and a residual plot -- the normal probability plot is not a diagonal approximately straight line, and the residuals are not very randomly scattered, so the linear regression model may not be appropriate in this case.
residuals<-resid(observet_stopt_model)
hist(residuals)
qqnorm(residuals)
plot(fitted(observet_stopt_model), residuals)


????
## Exclude outliers whose standard residuals are greater than 2:
standard_residuals <- rstandard(observet_stopt_model)
plot(fitted(observet_stopt_model), standard_residuals)

observet_stopt <- NYPD[c("OBSERVED_DURATION_MINUTES", "STOP_DURATION_MINUTES")]
observet_stopt_stdres <- cbind(observet_stopt, standard_residuals)
dim(observet_stopt_stdres)

observet_stopt_analysis <- observet_stopt_stdres[observet_stopt_stdres$standard_residuals < 2,]


#The lm() function only gives us the the intercept and slope coefficient for the regression line 
#When we run the lm() function within the summary() function the results of the linear regression analysis will be produced.
summary(lm(STOP_DURATION_MINUTES ~ OBSERVED_DURATION_MINUTES, data = observet_stopt_analysis))
????
  
aaa <- NYPD[NYPD$OBSERVED_DURATION_MINUTES<=35 && NYPD$STOP_DURATION_MINUTES <=50,]
cor(aaa$OBSERVED_DURATION_MINUTES,aaa$STOP_DURATION_MINUTES)
model <- lm(STOP_DURATION_MINUTES ~ OBSERVED_DURATION_MINUTES, data = aaa)
print(model)
residuals<-resid(model)
hist(residuals)
qqnorm(residuals)
plot(fitted(model), residuals)
```

```{r}
### Linear Regression 2: Observe Time VS. Suspect Height


## First roughly observe the linear relationship between Observe Mins and Suspect Height

# scatter plot of height(x) vs. observe time(y), done above
ggplot(NYPD, aes(SUSPECT_HEIGHT, OBSERVED_DURATION_MINUTES)) + geom_point() + labs(title="Relation between Suspect Height and Observed Time ", y="observed duration mins", x="suspect height")

# Here we use the same way as previously in part 1 to define and exclude outliers based on context; outliers: observed mins >35
sample_h_observet <- NYPD[!is.na(NYPD$SUSPECT_HEIGHT) & NYPD$OBSERVED_DURATION_MINUTES<=35,]

# calculate the correlation -- seems a very weak negative correlation
corr_h_observet <- cor(sample_h_observet$SUSPECT_HEIGHT, sample_h_observet$OBSERVED_DURATION_MINUTES)
print(paste("correlation between suspect height and observed mins is",corr_h_observet))

# generate a line of best fit -- the line is approximately horizontal, meaning observed mins may not change a lot as height varies
ggplot(sample_h_observet, aes(SUSPECT_HEIGHT, OBSERVED_DURATION_MINUTES)) + geom_point() + geom_smooth(method="lm")



## Build the linear regression model and check whether the residuals fit the assumptions
h_observet_model <- lm(OBSERVED_DURATION_MINUTES ~ SUSPECT_HEIGHT, data = sample_h_observet)
print(h_observet_model)

# generate histogram, normal probability plot of residuals and a residual plot -- the histogram is not normally distributed and the normal probability plot is not approximately a straight line, so the linear regression model may not be appropriate in this case.
residuals<-resid(h_observet_model)
hist(residuals)
qqnorm(residuals)
plot(fitted(h_observet_model), residuals)

# Calculate and plot the standard residuals
standard_residuals <- rstandard(h_observet_model)
plot(fitted(h_observet_model), standard_residuals)

????
## Exclude outliers whose standard residuals are greater than 2:

observet_stopt <- NYPD[c("OBSERVED_DURATION_MINUTES", "STOP_DURATION_MINUTES")]
observet_stopt_stdres <- cbind(observet_stopt, standard_residuals)
dim(observet_stopt_stdres)

observet_stopt_analysis <- observet_stopt_stdres[observet_stopt_stdres$standard_residuals < 2,]
```

```{r}
### Comparison of Means T-test 1: mean observed duration time of 2 eye colors(a common eye color -- Black and an uncommon eye color -- Blue)

## how we define common and uncommon: 1025 observations of "black eye", 157 observations of "blue eye"
unique(NYPD$SUSPECT_EYE_COLOR)
table(NYPD$SUSPECT_EYE_COLOR)


## subset the vectors that we are going to do the t-test
# We use the same method as previously in part 1 to exclude outliers in observed time(>35). We have to exclude that before the test, otherwise the mean would be severely raised by the outliers
sample_eye_observet <- NYPD %>%
       select(OBSERVED_DURATION_MINUTES, SUSPECT_EYE_COLOR) %>%
       filter(SUSPECT_EYE_COLOR %in% c("BRO", "BLU"), OBSERVED_DURATION_MINUTES<=35)


## Calculate the mean observed time by eye color
mean_observet_by_eyecolor <- sample_eye_observet %>%
       group_by(SUSPECT_EYE_COLOR) %>%
       summarize(mean_observet = mean(OBSERVED_DURATION_MINUTES, na.rm=TRUE))
print(mean_observet_by_eyecolor)


## Create a comparative box plot of Observed Duration Minutes by Eye Color
ggplot(sample_eye_observet, aes(OBSERVED_DURATION_MINUTES, SUSPECT_EYE_COLOR)) + geom_boxplot(colour = "blue", fill="grey") + ggtitle("Observed Time by Eye Color")


## Conduct a comparison of means t-test:
t.test(OBSERVED_DURATION_MINUTES~SUSPECT_EYE_COLOR, data=sample_eye_observet, equal.var=FALSE)

# from the t-test result we see, p-value is much higher than 0.05 which implies there is no statistical significant difference in observed time means of the 2 different eye colors "blue" and "black"; the 95% confidence intervals also include 0(no difference). We cannot reject null hypothesis.
```

```{r}
### Comparison of Means T-test 2: mean observed duration time of thin suspects and heavy suspects (body build type)

unique(NYPD$SUSPECT_BODY_BUILD_TYPE)
table(NYPD$SUSPECT_BODY_BUILD_TYPE) # Thin suspects are far more than heavy suspects.

# We will use all the data to conduct the test first, and then we do again without outliers(observed mins >35)

## subset the vectors that we are going to do the t-test
all_sample_body_observet <- NYPD %>%
       select(OBSERVED_DURATION_MINUTES, SUSPECT_BODY_BUILD_TYPE) %>%
       filter(SUSPECT_BODY_BUILD_TYPE %in% c("HEA", "THN"))


## Calculate the mean observed time by body build type
all_mean_observet_by_body <- sample_body_observet %>%
       group_by(SUSPECT_BODY_BUILD_TYPE) %>%
       summarize(all_mean_observet = mean(OBSERVED_DURATION_MINUTES, na.rm=TRUE))
print(all_mean_observet_by_body)


## Create a comparative box plot of Observed Duration Minutes by Body Build Type
ggplot(all_sample_body_observet, aes(OBSERVED_DURATION_MINUTES, SUSPECT_BODY_BUILD_TYPE)) + geom_boxplot(colour = "orange", fill="grey") + ggtitle("Observed Time by Body Build Type")


## Conduct a comparison of means t-test:
t.test(OBSERVED_DURATION_MINUTES~SUSPECT_BODY_BUILD_TYPE, data=all_sample_body_observet, equal.var=FALSE)

# from the t-test result we see, p-value is much higher than 0.05 which implies there is no statistical significant difference in observed time means of thin suspects and heavy suspects(with all data including outliers). Even though we could see obvious difference in the computed means(Thin 33.04 mins, Heavy 10.99 mins), we cannot conclude the mean observed time is different in these 2 groups.





# Then do it again excluding outliers: we use the same method as previously in part 1 to exclude outliers in observed time(>35), which is defined according to context. 
sample_body_observet <- NYPD %>%
       select(OBSERVED_DURATION_MINUTES, SUSPECT_BODY_BUILD_TYPE) %>%
       filter(SUSPECT_BODY_BUILD_TYPE %in% c("HEA", "THN"), OBSERVED_DURATION_MINUTES<=35)


mean_observet_by_body <- sample_body_observet %>%
       group_by(SUSPECT_BODY_BUILD_TYPE) %>%
       summarize(mean_observet = mean(OBSERVED_DURATION_MINUTES, na.rm=TRUE))
print(mean_observet_by_body)



ggplot(sample_body_observet, aes(OBSERVED_DURATION_MINUTES, SUSPECT_BODY_BUILD_TYPE)) + geom_boxplot(colour = "orange", fill="grey") + ggtitle("Observed Time by Body Build Type")


t.test(OBSERVED_DURATION_MINUTES~SUSPECT_BODY_BUILD_TYPE, data=sample_body_observet, equal.var=FALSE)

# The p-value is much higher this time(0.98 >>> 0.05), we are still rejecting the null hypothesis. From the 2 tests above, we could conclude there is no statistical significant difference in observed duration minutes of thin and heavy suspects.
```
```{r}
#Conduct a Chi-Squared Test of Independence
chisq.test(analysis_vars2$OFFICER_IN_UNIFORM_FLAG, analysis_vars2$SUSPECT_ARRESTED_FLAG)
```